<a href="https://colab.research.google.com/github/KlausPeace95/Deep-Learning/blob/main/tf_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.15.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.97095317,  0.15480427, -0.1906796 ,  0.1859858 , -0.02711892,
        -0.8284084 , -1.2057344 , -0.051815  , -0.22894105,  0.32037157]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.24745019, 0.10940541, 0.07744566, 0.11287059, 0.09120751,
        0.04092936, 0.02806496, 0.08898263, 0.07453845, 0.12910521]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

3.1959076

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy']
              )

In [10]:
#TRANING AND EVALUATION

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2899 - accuracy: 0.9169
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1389 - accuracy: 0.9587
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1051 - accuracy: 0.9691
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0850 - accuracy: 0.9742
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0749 - accuracy: 0.9764


In [15]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0700 - accuracy: 0.9788 - 494ms/epoch - 2ms/step


[0.07000849395990372, 0.9787999987602234]

In [16]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.2070179e-07, 1.0195599e-09, 8.2790966e-06, 1.7956017e-04,
        1.1671410e-11, 6.3059169e-08, 1.8788384e-12, 9.9980241e-01,
        3.1157944e-07, 9.0278227e-06],
       [6.8511198e-08, 1.6878363e-04, 9.9969542e-01, 1.1963725e-04,
        5.3964943e-15, 9.8303090e-06, 1.2068297e-07, 1.3949714e-13,
        6.0425186e-06, 1.9170132e-12],
       [3.6986074e-07, 9.9471480e-01, 5.0771149e-04, 1.0380784e-05,
        1.9743119e-04, 3.9169758e-05, 7.7221724e-05, 3.7021262e-03,
        7.4997020e-04, 9.0076475e-07],
       [9.9990463e-01, 2.5310817e-10, 3.3355416e-05, 6.6574148e-07,
        3.1776551e-07, 2.4435760e-05, 1.1449184e-05, 2.4023720e-05,
        4.3492307e-08, 1.0784061e-06],
       [4.5918823e-06, 2.8542113e-10, 1.2492563e-04, 3.7595066e-07,
        9.9670488e-01, 1.8524752e-06, 3.8675234e-06, 1.5897084e-04,
        8.5473494e-06, 2.9918700e-03]], dtype=float32)>