<a href="https://colab.research.google.com/github/KlausPeace95/Deep-Learning/blob/main/tfTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
tensor_1d = np.array([1.3, 1, 4.0, 23.99])
tensor_1d

array([ 1.3 ,  1.  ,  4.  , 23.99])

In [9]:
tensor_1d[2] # prints 4.

4.0

In [10]:
tensor_2d = np.array([[2,3,5],[0,-4,8],[6,1,-1]])
tensor_2d

array([[ 2,  3,  5],
       [ 0, -4,  8],
       [ 6,  1, -1]])

In [12]:
tensor_2d[2][0]

6

In [17]:
tensor_zero = np.zeros((3, 4), dtype=int)
tensor_zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
# Tensor Handling and Manipulations

import tensorflow as tf
tf.compat.v1.disable_eager_execution()

matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype = 'int32')

print('Matrix1')
print (matrix1)
print('\n Matrix2')
print (matrix2)

matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
print('\n Matrix1 * Matrix2')
matrix_product = tf.matmul(matrix1, matrix2)
print(matrix_product)
print('\n Matrix1 + Matrix2')
matrix_sum = tf.add(matrix1,matrix2)
print(matrix_sum)
print('\n Matrix3')
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype = 'float32')
print (matrix_3)

print('\n det(Matrix3)')
matrix_det = tf.linalg.det(matrix_3)
print(matrix_det)

with tf.compat.v1.Session() as sess:
   result1 = sess.run(matrix_product)
   result2 = sess.run(matrix_sum)
   result3 = sess.run(matrix_det)

print('\n Session Results')

print (result1)
print (result2)
print (result3)

Matrix1
[[2 2 2]
 [2 2 2]
 [2 2 2]]

 Matrix2
[[1 1 1]
 [1 1 1]
 [1 1 1]]

 Matrix1 * Matrix2
Tensor("MatMul_2:0", shape=(3, 3), dtype=int32)

 Matrix1 + Matrix2
Tensor("Add_2:0", shape=(3, 3), dtype=int32)

 Matrix3
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]

 det(Matrix3)
Tensor("MatrixDeterminant_2:0", shape=(), dtype=float32)

 Session Results
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
55.999992
